services:
    database:
        image: mariadb
        restart: always
        container_name: email-orders-database
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - ${DB_PORT}:3306
        volumes:
            - ./.db-data:/var/lib/mysql
        networks:
            - private

    backend:
        build:
            context: backend
            dockerfile: Dockerfile
        image: email-orders:backend
        container_name: email-orders-backend
        env_file: './.env'
        ports:
            - ${APP_PORT}:${APP_PORT}
        volumes:
            - ./backend:/var/www/html
        command: make start port=${APP_PORT}
        networks:
            - public
            - private
        depends_on:
            - database

    frontend:
        build:
            context: frontend
            dockerfile: Dockerfile
            args:
                - BACKEND_URL=${BACKEND_URL}
                - IS_DOCKER=${IS_DOCKER}
                - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
                - MAIL_FROM_NAME=${MAIL_FROM_NAME}
        image: email-orders:frontend
        container_name: email-orders-frontend
        volumes:
            - ./frontend/:/frontend/
        ports:
            - ${FRONTEND_PORT}:${FRONTEND_PORT}
        command: npm run docker:start:${APP_ENV:-local} -- -p ${FRONTEND_PORT}
        depends_on:
            - backend
        networks:
            - public

networks:
    private:
    public:
